# -*- coding: utf-8 -*-
"""Basics Python boolean functions and lists.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16MlRL9GrHZZvUVX_BZzS6RkPentoL0qp
"""

bool()

type(True)

type(False)

#boolean functions
string_is = 'Achuth Dintakurthi'
print(string_is.isalnum())#if all chars are numbers
print(string_is.isalpha())#if all chars in the string all alphabetic
print(string_is.isdigit())#if it contains digits returns true
print(string_is.istitle())#contains title words
print(string_is.isupper())#if it contains uppper case returns true
print(string_is.islower())#if it contains lower
print(string_is.isspace())#if string contains spaces
print(string_is.startswith('A'))
print(string_is.endswith('i'))

string2 = '12344'
print(string2.isnumeric())
string3 = '    '
print(string3.isspace())

print(True and True)
print(True and False)
print(False and False)
print(True or False)

#in this type we can use the boolean operators
string1 = '     '
string2 = '12344'
string1.isspace() and string2.isnumeric()

"""## ***LISTS***"""

#lists are mutable and they are orderable
list1=[]
type(list1)

list2 = list()
type(list2)

#lists may contains different data types
list3 = ['maths',1,2,3]
type(list3)

#append funvtion is used to add elemets or a list also
list4 = [5,6,7]
#list3.append(list4)
print(list3)
#in the above case list4 is alos an element of list3 after we appending
#adding element by element in the list3 from list4 by using the for loop
for i in range(len(list4)):
  list3.append(list4[i])
print(list3)

#indexing in list
print(list3)
#accessing the 5 value in the list which is present in the sublist
print(list3[4][0])
#indexing starts from 0 
#accessing more than 1 elements in lists
#list_name[startindex:Endindex+1] syntax for accessing
#in the below it will print 1,2,3and[5,6,7]
print(list3[1:5])

#adding the elements to list in specific position 
# by using  the insert function
print(list3)
#adding my name['Achuth'] at index of 2
list3.insert(2,'Achuth')
print(list3)

#adding the elemts by elemnts with out using for loop we use extend method
list_new = [1,2,3,4,5]
list_new.extend([6,7])
print(list_new)

#operations on list
#sum in list
print("sum is {}".format(sum(list_new)))
#deleting the last element in list bu pop()
list_new.pop()

#return the frequency of the element in a list
list_occ = [1,1,1,1,222,222,222]
list_occ.count(1)

#length of the list
print(len(list_occ))

#minimum in list
print(min(list4))
#maximum in the list
print(max(list4))

